scene: add support for custom shaders in mirrors, images and text
tesselslate/waywall pull request #5
Opened 2024-12-22 23:38 UTC by dariasc

This adds a new config field `shaders`  in which you can add custom shaders:
```
shaders = {
        ["pie_chart"] = {
                fragment = read_file("pie_chart.frag"),
        },
},
```

2024-12-23 21:42 UTC, tesselslate requested changes
There's one minor memory leak and a few style nits, but this looks good otherwise! Thanks for your work.

There is one fairly annoying issue to solve, though, which is that shaders are only ever loaded from the configuration file once at startup. I'm fine with resolving this myself once this PR is merged, since waywall has a weird system to try to atomically apply config updates.

2024-12-23 21:42 UTC, tesselslate commented on include/config/config.h
> +    char* name;
clang-format needs to get run (`ninja -C build clang-format` will run it on the entire project) to fix these and a few other small formatting differences

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/api.c
> +        shader = strdup(luaL_checkstring(L, ARG_SHADER));
This string never gets freed, which causes a small memory leak.

It should be possible to avoid calling `strdup` here because this particular string remains on the Lua stack until the end of the function, so the string returned from `luaL_checkstring` is valid until this function is exited.

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +    .shaders = {0}
There should be a trailing comma here, or else `clang-format` will make this struct initializer pretty ugly

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +    free(cfg->shaders.data);
It's technically fine on C11 to `free(NULL)` if the user hasn't provided a `shaders` table but I prefer to have non-null checks

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +        // 4 (IDX_SHADER_VAL) : config.shaders[key] (should be a string)
typo: `should be a table`

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +    // const int IDX_SHADER_VAL = 4;
nit: `// const int IDX_SHADER_VAL = 4;` can be removed since it's not used, I'm fine with the below `stack state` comment using its name

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +        if (get_string(cfg, "fragment", &fragment, "shaders[].fragment", false)) {
I think both the vertex and fragment shaders should probably be required. Are there any use cases for having a fragment shader but not a vertex shader, and vice versa?

2024-12-23 21:42 UTC, tesselslate commented on waywall/scene.c
> +int shader_find_index(struct scene* scene, char* key) {
Both this and `shader_create` should be static functions

2024-12-23 21:42 UTC, tesselslate commented on waywall/config/config.c
> +        if (get_string(cfg, "fragment", &fragment, "shaders[].fragment", false)) {
Ah, never mind, I see that you default to using the texcopy implementations if one isn't provided. That is a pretty sensible default.

2024-12-24 19:05 UTC, dariasc commented
> There is one fairly annoying issue to solve, though, which is that shaders are only ever loaded from the configuration file once at startup. I'm fine with resolving this myself once this PR is merged, since waywall has a weird system to try to atomically apply config updates.

Might be better for the `fragment` and `vertex` fields to be filenames instead. Although I guess that would have the same issue if the underlying file changes.

2024-12-24 20:36 UTC, tesselslate commented
> Might be better for the `fragment` and `vertex` fields to be filenames instead. Although I guess that would have the same issue if the underlying file changes.

I think accepting the source code as a string is fine, though I might add a function to the `helpers` module to make reading files from `~/.config/waywall` more convenient.

2024-12-24 20:36 UTC, tesselslate approved these changes

2024-12-24 20:37 UTC, merged

2024-12-24 20:37 UTC, tesselslate commented
Thanks for the PR!